-- ════════════════════════════════════════════════════════════════
-- ระบบตรวจรับงานตัดต้นไม้ กฟภ. — Supabase schema
-- วิธีใช้: Supabase Dashboard → SQL Editor → วางทั้งไฟล์ → Run (รันซ้ำได้)
-- วิธีสร้างผู้ใช้: ดูท้ายไฟล์
-- ════════════════════════════════════════════════════════════════
create extension if not exists pgcrypto;

-- ── การไฟฟ้า (เพิ่มแห่งใหม่ = insert แถวใหม่) ──
create table if not exists offices (
  id   text primary key,              -- รหัสสั้น ใช้ต่อท้ายอีเมลภายใน เช่น kce
  name text not null
);
insert into offices (id, name) values ('kce', 'กฟส.คำชะอี'), ('ktw', 'กฟส.กันทรวิชัย') on conflict (id) do nothing;

-- ── ผู้ใช้ (1 แถวต่อ 1 auth.users) ──
-- login ด้วยชื่อผู้ใช้: frontend แปลงเป็นอีเมลภายใน {username}@{office_id}.local
create table if not exists profiles (
  id        uuid primary key references auth.users on delete cascade,
  office_id text not null references offices,
  username  text not null,
  full_name text not null default '',
  role      text not null check (role in ('inspector', 'contractor')),
  company   text,                      -- ชื่อบริษัท/หจก. (ผู้รับจ้าง)
  is_admin  boolean not null default false,   -- ผู้ดูแลระบบ: เพิ่มการไฟฟ้า/ผู้ใช้ได้ทุกแห่ง
  unique (office_id, username)
);
alter table profiles add column if not exists is_admin boolean not null default false;   -- สำหรับฐานข้อมูลที่สร้างก่อนมีคอลัมน์นี้

create table if not exists feeders (
  id         uuid primary key default gen_random_uuid(),
  office_id  text not null references offices,
  code       text not null,
  line_name  text not null default '',
  created_by uuid references profiles default auth.uid(),
  created_at timestamptz not null default now(),
  closed_at  timestamptz,              -- สถานะอื่น (กำลังตรวจ/รอแก้) คำนวณที่ client
  unique (office_id, code)
);

create table if not exists feeder_contractors (
  feeder_id     uuid references feeders on delete cascade,
  contractor_id uuid references profiles on delete cascade,
  primary key (feeder_id, contractor_id)
);

create table if not exists segments (
  id              uuid primary key default gen_random_uuid(),
  feeder_id       uuid not null references feeders on delete cascade,
  seq             int  not null,
  source_file     text,
  voltage         text,
  plan_trees      int,
  density_label   text,
  density_range   text,
  price_trees     int,
  length_km       numeric not null default 0,
  geom_geojson    jsonb not null,      -- {"type":"LineString","coordinates":[[lng,lat],…]}
  raw_description text,
  passed_at       timestamptz,         -- "ผ่านทั้งช่วง"
  passed_by       uuid references profiles,
  unique (feeder_id, seq)
);

create table if not exists inspection_rounds (
  id           uuid primary key default gen_random_uuid(),
  feeder_id    uuid not null references feeders on delete cascade,
  round_no     int  not null,
  started_at   timestamptz not null default now(),
  inspector_id uuid references profiles default auth.uid(),
  unique (feeder_id, round_no)
);

create table if not exists defects (
  id         uuid primary key default gen_random_uuid(),
  code_no    bigint generated by default as identity,   -- แสดงเป็น D-0412
  segment_id uuid not null references segments on delete cascade,
  feeder_id  uuid not null references feeders on delete cascade,
  round_id   uuid references inspection_rounds on delete set null,
  round_no   int  not null default 1,                    -- รอบตรวจล่าสุด (trigger อัปเดต)
  lat        double precision not null,
  lng        double precision not null,
  issue_type text not null,
  note       text,
  status     text not null default 'open' check (status in ('open', 'submitted', 'passed', 'rejected')),
  created_by uuid references profiles default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists defect_events (
  id         uuid primary key default gen_random_uuid(),
  defect_id  uuid not null references defects on delete cascade,
  kind       text not null check (kind in ('created', 'fix_submitted', 'passed', 'rejected')),
  round_no   int  not null,
  note       text,
  photos     jsonb not null default '[]',   -- [{"path":"MDA03R-04/<defect>/<event>_1.jpg","label":"IMG_1.jpg"}]
  actor_id   uuid references profiles default auth.uid(),
  created_at timestamptz not null default now()
);

-- ── งานตัดของผู้รับจ้าง (ก่อนตรวจรับ): started = เริ่มตัด + รูปก่อนตัด, finished = ตัดเสร็จ + รูปหลังตัด ──
create table if not exists segment_works (
  id         uuid primary key default gen_random_uuid(),   -- id มาจากเครื่อง (ส่งซ้ำตอน sync ได้)
  segment_id uuid not null references segments on delete cascade,
  feeder_id  uuid not null references feeders on delete cascade,
  kind       text not null check (kind in ('started', 'finished')),
  note       text,
  photos     jsonb not null default '[]',   -- [{"path":"MDA03R-04/<segment>/<work>_1.jpg","label":"IMG_1.jpg","lat":16.5,"lng":104.6}]
  actor_id   uuid references profiles default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz                      -- ผู้รับจ้างแก้ไขรายงานล่าสุดเมื่อ (null = ไม่เคยแก้)
);
alter table segment_works add column if not exists updated_at timestamptz;   -- สำหรับฐานข้อมูลที่สร้างก่อนมีคอลัมน์นี้

-- ── ขอดับไฟเพื่อตัดต้นไม้ (รายช่วง): ผู้รับจ้างขอ + เสนอวัน → ผู้ตรวจยืนยันวันดับไฟ หรือปฏิเสธ ──
create table if not exists outage_requests (
  id         uuid primary key default gen_random_uuid(),
  segment_id uuid not null references segments on delete cascade,
  feeder_id  uuid not null references feeders on delete cascade,
  want_date  date not null,                 -- วันที่ผู้รับจ้างขอ
  want_time  text not null default '',      -- ช่วงเวลา เช่น 09:00–12:00
  note       text,                          -- ตำแหน่ง/เหตุผล เช่น ต้นยางใหญ่คร่อมสาย เสาที่ 12–14
  status     text not null default 'requested' check (status in ('requested', 'confirmed', 'rejected')),
  ok_date    date,                          -- วันดับไฟที่ผู้ตรวจยืนยัน (อาจเลื่อนจากที่ขอ)
  ok_time    text,
  reply      text,                          -- ข้อความจากผู้ตรวจ / เหตุผลที่ปฏิเสธ
  actor_id   uuid references profiles default auth.uid(),
  created_at timestamptz not null default now(),
  decided_by uuid references profiles,
  decided_at timestamptz
);

create index if not exists segments_feeder_idx on segments (feeder_id);
create index if not exists works_feeder_idx    on segment_works (feeder_id);
create index if not exists outage_feeder_idx   on outage_requests (feeder_id);
create index if not exists defects_feeder_idx  on defects (feeder_id);
create index if not exists events_defect_idx   on defect_events (defect_id);

-- ── event → สถานะจุดบกพร่อง (ผู้รับจ้างแก้ defects เองไม่ได้ จึงให้ trigger ทำ) ──
create or replace function apply_defect_event() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  update defects set
    status   = case new.kind when 'created' then 'open' when 'fix_submitted' then 'submitted' else new.kind end,
    round_no = case when new.kind = 'fix_submitted' then round_no else new.round_no end
  where id = new.defect_id;
  return new;
end $$;
drop trigger if exists trg_defect_event on defect_events;
create trigger trg_defect_event after insert on defect_events for each row execute function apply_defect_event();

-- ════════════════════════════════════════════════════════════════
-- RLS
-- ════════════════════════════════════════════════════════════════
create or replace function my_office() returns text
language sql stable security definer set search_path = public as $$ select office_id from profiles where id = auth.uid() $$;
create or replace function is_inspector() returns boolean
language sql stable security definer set search_path = public as $$ select exists (select 1 from profiles where id = auth.uid() and role = 'inspector') $$;
-- เห็น feeder: ผู้ตรวจ = ทุก feeder ในการไฟฟ้าตน, ผู้รับจ้าง = เฉพาะที่ผูกไว้
create or replace function is_sysadmin() returns boolean
language sql stable security definer set search_path = public as $$ select coalesce((select is_admin from profiles where id = auth.uid()), false) $$;
create or replace function can_see_feeder(f uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from feeders x where x.id = f and x.office_id = my_office()
    and (is_inspector() or exists (select 1 from feeder_contractors fc where fc.feeder_id = f and fc.contractor_id = auth.uid())))
$$;
create or replace function can_edit_feeder(f uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select is_inspector() and exists (select 1 from feeders x where x.id = f and x.office_id = my_office())
$$;

alter table offices            enable row level security;
alter table profiles           enable row level security;
alter table feeders            enable row level security;
alter table feeder_contractors enable row level security;
alter table segments           enable row level security;
alter table inspection_rounds  enable row level security;
alter table defects            enable row level security;
alter table defect_events      enable row level security;
alter table segment_works      enable row level security;

-- หน้า login ต้องเห็นรายชื่อการไฟฟ้าก่อนล็อกอิน
drop policy if exists offices_read on offices;
drop policy if exists offices_write on offices;
create policy offices_read on offices for select using (true);
create policy offices_write on offices for insert to authenticated with check (is_sysadmin());
drop policy if exists offices_delete on offices;
create policy offices_delete on offices for delete to authenticated using (is_sysadmin());   -- FK กันลบถ้ายังมีผู้ใช้/งาน

drop policy if exists profiles_read on profiles;
-- ผู้ใช้เห็นคนในการไฟฟ้าตน · ผู้ดูแลระบบเห็นทุกคน (การสร้าง/แก้บัญชีทำผ่าน Edge Function admin-users เท่านั้น)
create policy profiles_read on profiles for select to authenticated using (office_id = my_office() or is_sysadmin());

drop policy if exists feeders_read on feeders;
drop policy if exists feeders_write on feeders;
create policy feeders_read  on feeders for select to authenticated using (can_see_feeder(id));
create policy feeders_write on feeders for all to authenticated
  using (is_inspector() and office_id = my_office()) with check (is_inspector() and office_id = my_office());

drop policy if exists fc_read on feeder_contractors;
drop policy if exists fc_write on feeder_contractors;
create policy fc_read  on feeder_contractors for select to authenticated using (can_see_feeder(feeder_id));
create policy fc_write on feeder_contractors for all to authenticated using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

drop policy if exists segments_read on segments;
drop policy if exists segments_write on segments;
create policy segments_read  on segments for select to authenticated using (can_see_feeder(feeder_id));
create policy segments_write on segments for all to authenticated using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

drop policy if exists rounds_read on inspection_rounds;
drop policy if exists rounds_write on inspection_rounds;
create policy rounds_read  on inspection_rounds for select to authenticated using (can_see_feeder(feeder_id));
create policy rounds_write on inspection_rounds for all to authenticated using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

drop policy if exists defects_read on defects;
drop policy if exists defects_write on defects;
create policy defects_read  on defects for select to authenticated using (can_see_feeder(feeder_id));
create policy defects_write on defects for all to authenticated using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

drop policy if exists events_read on defect_events;
drop policy if exists events_insp on defect_events;
drop policy if exists events_con_insert on defect_events;
create policy events_read on defect_events for select to authenticated
  using (exists (select 1 from defects d where d.id = defect_id and can_see_feeder(d.feeder_id)));
create policy events_insp on defect_events for all to authenticated
  using (exists (select 1 from defects d where d.id = defect_id and can_edit_feeder(d.feeder_id)))
  with check (exists (select 1 from defects d where d.id = defect_id and can_edit_feeder(d.feeder_id)));
-- ผู้รับจ้าง: insert ได้อย่างเดียว เฉพาะ fix_submitted ของจุดที่รอแก้/ไม่ผ่าน ใน feeder ตน
create policy events_con_insert on defect_events for insert to authenticated
  with check (kind = 'fix_submitted' and actor_id = auth.uid()
    and exists (select 1 from defects d where d.id = defect_id and d.status in ('open', 'rejected') and can_see_feeder(d.feeder_id)));

drop policy if exists works_read on segment_works;
drop policy if exists works_con_insert on segment_works;
create policy works_read on segment_works for select to authenticated using (can_see_feeder(feeder_id));
-- ผู้รับจ้าง: insert ได้อย่างเดียว เฉพาะช่วงของ feeder ที่ตนรับงาน
create policy works_con_insert on segment_works for insert to authenticated
  with check (actor_id = auth.uid() and not is_inspector() and can_see_feeder(feeder_id)
    and exists (select 1 from segments s where s.id = segment_id and s.feeder_id = segment_works.feeder_id));
-- ผู้รับจ้างแก้/ลบได้เฉพาะรายงานของตน (แอปกันไว้อีกชั้น: เฉพาะช่วงที่ยังไม่ถูกตรวจ)
drop policy if exists works_con_update on segment_works;
drop policy if exists works_con_delete on segment_works;
create policy works_con_update on segment_works for update to authenticated
  using (actor_id = auth.uid() and can_see_feeder(feeder_id)) with check (actor_id = auth.uid() and can_see_feeder(feeder_id));
create policy works_con_delete on segment_works for delete to authenticated using (actor_id = auth.uid() and can_see_feeder(feeder_id));

alter table outage_requests enable row level security;
drop policy if exists outage_read on outage_requests;
drop policy if exists outage_con_insert on outage_requests;
drop policy if exists outage_con_delete on outage_requests;
drop policy if exists outage_insp on outage_requests;
create policy outage_read on outage_requests for select to authenticated using (can_see_feeder(feeder_id));
-- ผู้รับจ้าง: ขอได้เฉพาะช่วงของ feeder ที่ตนรับงาน · ยกเลิก (ลบ) ได้เฉพาะคำขอของตนที่ยังรอยืนยัน
create policy outage_con_insert on outage_requests for insert to authenticated
  with check (actor_id = auth.uid() and not is_inspector() and status = 'requested' and can_see_feeder(feeder_id)
    and exists (select 1 from segments s where s.id = segment_id and s.feeder_id = outage_requests.feeder_id));
create policy outage_con_delete on outage_requests for delete to authenticated
  using (actor_id = auth.uid() and status = 'requested' and can_see_feeder(feeder_id));
-- ผู้ตรวจ: ยืนยันวัน / ปฏิเสธ
create policy outage_insp on outage_requests for update to authenticated
  using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

-- ── ภาพรวมทุกการไฟฟ้า (หน้า login, ไม่ต้องล็อกอิน, ดูอย่างเดียว) ──
-- คืนเฉพาะตัวเลขสรุป + สถานะรายช่วง: ไม่มีรูป พิกัด ชื่อผู้ใช้ หรือหมายเหตุ
-- สถานะช่วงต้องตรงกับ segSt() ใน index.html: defect > pass > cut > cutting > none
create or replace function public_overview() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(x order by x.office_name, x.code), '[]') from (
    select f.id, o.id office_id, o.name office_name, f.code, f.line_name, f.closed_at,
      (select coalesce(p.company, p.full_name) from feeder_contractors fc join profiles p on p.id = fc.contractor_id where fc.feeder_id = f.id limit 1) contractor,
      (select count(*) from defects d where d.feeder_id = f.id and d.status in ('open', 'rejected')) out_n,
      (select count(*) from defects d where d.feeder_id = f.id and d.status = 'submitted') rev_n,
      (select count(*) from defects d where d.feeder_id = f.id) def_n,
      (select coalesce(json_agg(json_build_object('seq', s.seq, 'km', s.length_km, 'st',
        case when exists (select 1 from defects d where d.segment_id = s.id and d.status <> 'passed') then 'defect'
             when s.passed_at is not null or exists (select 1 from defects d where d.segment_id = s.id) then 'pass'
             when exists (select 1 from segment_works w where w.segment_id = s.id and w.kind = 'finished') then 'cut'
             when exists (select 1 from segment_works w where w.segment_id = s.id and w.kind = 'started') then 'cutting'
             else 'none' end) order by s.seq), '[]') from segments s where s.feeder_id = f.id) segs
    from feeders f join offices o on o.id = f.office_id) x
$$;
revoke all on function public_overview() from public;
grant execute on function public_overview() to anon, authenticated;

-- ── ไส้ในงาน 1 Feeder (เปิดจากหน้าภาพรวม, ไม่ต้องล็อกอิน, ดูอย่างเดียว) ──
-- ช่วง + งานตัด + จุดบกพร่อง + ประวัติ พร้อม path รูป (ผู้ตรวจแสดงเป็น "ผู้ตรวจ" ไม่เปิดชื่อบุคคล)
create or replace function public_feeder(fid uuid) returns json
language sql stable security definer set search_path = public as $$
  select json_build_object('id', f.id, 'code', f.code, 'line', f.line_name, 'office', f.office_id, 'closed_at', f.closed_at, 'imported_at', f.created_at,
    'contractor', (select coalesce(p.company, p.full_name) from feeder_contractors fc join profiles p on p.id = fc.contractor_id where fc.feeder_id = f.id limit 1),
    'segments', (select coalesce(json_agg(json_build_object('id', s.id, 'seq', s.seq, 'voltage', s.voltage, 'plan_trees', s.plan_trees, 'density_label', s.density_label,
        'density_range', s.density_range, 'price_trees', s.price_trees, 'length_km', s.length_km, 'geom', s.geom_geojson, 'source_file', s.source_file, 'passed_at', s.passed_at,
        'works', (select coalesce(json_agg(json_build_object('id', w.id, 'kind', w.kind, 'at', w.created_at, 'edited', w.updated_at, 'note', w.note, 'photos', w.photos,
            'who', (select coalesce(p.company, p.full_name) from profiles p where p.id = w.actor_id)) order by w.created_at), '[]') from segment_works w where w.segment_id = s.id)
      ) order by s.seq), '[]') from segments s where s.feeder_id = f.id),
    'defects', (select coalesce(json_agg(json_build_object('id', d.id, 'code_no', d.code_no, 'segment_id', d.segment_id, 'lat', d.lat, 'lng', d.lng,
        'issue_type', d.issue_type, 'status', d.status, 'round_no', d.round_no,
        'events', (select coalesce(json_agg(json_build_object('kind', e.kind, 'round_no', e.round_no, 'note', e.note, 'photos', e.photos, 'at', e.created_at,
            'who', (select case when p.role = 'inspector' then 'ผู้ตรวจ' else coalesce(p.company, p.full_name) end from profiles p where p.id = e.actor_id)) order by e.created_at), '[]')
          from defect_events e where e.defect_id = d.id)
      ) order by d.code_no), '[]') from defects d where d.feeder_id = f.id))
  from feeders f where f.id = fid
$$;
revoke all on function public_feeder(uuid) from public;
grant execute on function public_feeder(uuid) to anon, authenticated;

-- ════════════════════════════════════════════════════════════════
-- STORAGE: bucket "photos" (private)
--   จุดบกพร่อง: {feeder_code}/{defect_id}/{event_id}_{n}.jpg · งานตัด: {feeder_code}/{segment_id}/{work_id}_{n}.jpg
-- สิทธิ์ตรวจจากโฟลเดอร์ที่ 2 (defect_id หรือ segment_id) → feeder ของมัน
-- ════════════════════════════════════════════════════════════════
insert into storage.buckets (id, name, public) values ('photos', 'photos', false) on conflict (id) do nothing;

create or replace function photo_feeder(folder text) returns uuid
language sql stable security definer set search_path = public as $$
  select coalesce((select feeder_id from defects where id::text = folder), (select feeder_id from segments where id::text = folder))
$$;
drop policy if exists photos_read on storage.objects;
drop policy if exists photos_insert on storage.objects;
create policy photos_read on storage.objects for select to authenticated
  using (bucket_id = 'photos' and can_see_feeder(photo_feeder((storage.foldername(name))[2])));
create policy photos_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'photos' and can_see_feeder(photo_feeder((storage.foldername(name))[2])));
-- ไส้ในงานเปิดสาธารณะ (หน้าภาพรวม): ทุกคนอ่านรูปได้ (เขียน/ลบยังจำกัดตามด้านบน)
drop policy if exists photos_public_read on storage.objects;
create policy photos_public_read on storage.objects for select to anon, authenticated using (bucket_id = 'photos');
-- ลบงาน: ผู้ตรวจลบรูปของ feeder ในการไฟฟ้าตน (ต้องลบรูปก่อนลบ feeder เพราะอ้าง defect/segment)
drop policy if exists photos_delete on storage.objects;
create policy photos_delete on storage.objects for delete to authenticated
  using (bucket_id = 'photos' and can_edit_feeder(photo_feeder((storage.foldername(name))[2])));

-- ════════════════════════════════════════════════════════════════
-- REALTIME
-- ════════════════════════════════════════════════════════════════
do $$ begin
  alter publication supabase_realtime add table feeders, segments, defects, defect_events;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table segment_works;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table outage_requests;
exception when duplicate_object then null; end $$;

-- ════════════════════════════════════════════════════════════════
-- สร้างผู้ใช้ (ทำโดยผู้ดูแล — ผู้ใช้ไม่ต้องมีอีเมลจริง)
-- 1) Dashboard → Authentication → Users → Add user → Create new user
--      Email:    {ชื่อผู้ใช้}@{รหัสการไฟฟ้า}.local   เช่น somchai.j@kce.local
--      Password: ตั้งให้ผู้ใช้   ✓ Auto Confirm User
-- 2) รัน SQL ผูกโปรไฟล์ (แก้ค่าตามจริง):
--
-- insert into profiles (id, office_id, username, full_name, role, company)
-- select id, 'kce', 'somchai.j', 'สมชาย ใจดี', 'inspector', null from auth.users where email = 'somchai.j@kce.local';
--
-- insert into profiles (id, office_id, username, full_name, role, company)
-- select id, 'kce', 'romyen.co', 'ผู้ประสานงาน ร่มเย็น', 'contractor', 'หจก. ร่มเย็นการโยธา' from auth.users where email = 'romyen.co@kce.local';
--
-- เพิ่มการไฟฟ้าใหม่: insert into offices values ('xxx', 'กฟส.ชื่อใหม่');
--
-- ตั้งผู้ดูแลระบบ (จัดการการไฟฟ้าและผู้ใช้ในแอปได้ — ต้อง deploy Edge Function supabase/functions/admin-users ด้วย):
-- update profiles set is_admin = true where office_id = 'kce' and username = 'admin';
-- ════════════════════════════════════════════════════════════════
