-- ════════════════════════════════════════════════════════════════
-- ระบบตรวจรับงานตัดต้นไม้ กฟภ. — Supabase schema
-- วิธีใช้: Supabase Dashboard → SQL Editor → วางทั้งไฟล์ → Run (รันซ้ำได้)
-- วิธีสร้างผู้ใช้: ดูท้ายไฟล์
-- ════════════════════════════════════════════════════════════════
create extension if not exists pgcrypto;

-- ── การไฟฟ้า (เพิ่มแห่งใหม่ = insert แถวใหม่) ──
create table if not exists offices (
  id   text primary key,              -- รหัสสั้น ใช้ต่อท้ายอีเมลภายใน เช่น kce
  name text not null
);
insert into offices (id, name) values ('kce', 'กฟส.คำชะอี'), ('ktw', 'กฟส.กันทรวิชัย') on conflict (id) do nothing;

-- ── ผู้ใช้ (1 แถวต่อ 1 auth.users) ──
-- login ด้วยชื่อผู้ใช้: frontend แปลงเป็นอีเมลภายใน {username}@{office_id}.local
create table if not exists profiles (
  id        uuid primary key references auth.users on delete cascade,
  office_id text not null references offices,
  username  text not null,
  full_name text not null default '',
  role      text not null check (role in ('inspector', 'contractor')),
  company   text,                      -- ชื่อบริษัท/หจก. (ผู้รับจ้าง)
  is_admin  boolean not null default false,   -- ผู้ดูแลระบบ: เพิ่มการไฟฟ้า/ผู้ใช้ได้ทุกแห่ง
  unique (office_id, username)
);
alter table profiles add column if not exists is_admin boolean not null default false;   -- สำหรับฐานข้อมูลที่สร้างก่อนมีคอลัมน์นี้

create table if not exists feeders (
  id         uuid primary key default gen_random_uuid(),
  office_id  text not null references offices,
  code       text not null,
  line_name  text not null default '',
  created_by uuid references profiles default auth.uid(),
  created_at timestamptz not null default now(),
  closed_at  timestamptz,              -- สถานะอื่น (กำลังตรวจ/รอแก้) คำนวณที่ client
  unique (office_id, code)
);

create table if not exists feeder_contractors (
  feeder_id     uuid references feeders on delete cascade,
  contractor_id uuid references profiles on delete cascade,
  primary key (feeder_id, contractor_id)
);

create table if not exists segments (
  id              uuid primary key default gen_random_uuid(),
  feeder_id       uuid not null references feeders on delete cascade,
  seq             int  not null,
  source_file     text,
  voltage         text,
  plan_trees      int,
  density_label   text,
  density_range   text,
  price_trees     int,
  length_km       numeric not null default 0,
  geom_geojson    jsonb not null,      -- {"type":"LineString","coordinates":[[lng,lat],…]}
  raw_description text,
  passed_at       timestamptz,         -- "ผ่านทั้งช่วง"
  passed_by       uuid references profiles,
  unique (feeder_id, seq)
);

create table if not exists inspection_rounds (
  id           uuid primary key default gen_random_uuid(),
  feeder_id    uuid not null references feeders on delete cascade,
  round_no     int  not null,
  started_at   timestamptz not null default now(),
  inspector_id uuid references profiles default auth.uid(),
  unique (feeder_id, round_no)
);

create table if not exists defects (
  id         uuid primary key default gen_random_uuid(),
  code_no    bigint generated by default as identity,   -- แสดงเป็น D-0412
  segment_id uuid not null references segments on delete cascade,
  feeder_id  uuid not null references feeders on delete cascade,
  round_id   uuid references inspection_rounds on delete set null,
  round_no   int  not null default 1,                    -- รอบตรวจล่าสุด (trigger อัปเดต)
  lat        double precision not null,
  lng        double precision not null,
  issue_type text not null,
  note       text,
  status     text not null default 'open' check (status in ('open', 'submitted', 'passed', 'rejected')),
  created_by uuid references profiles default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists defect_events (
  id         uuid primary key default gen_random_uuid(),
  defect_id  uuid not null references defects on delete cascade,
  kind       text not null check (kind in ('created', 'fix_submitted', 'passed', 'rejected')),
  round_no   int  not null,
  note       text,
  photos     jsonb not null default '[]',   -- [{"path":"MDA03R-04/<defect>/<event>_1.jpg","label":"IMG_1.jpg"}]
  actor_id   uuid references profiles default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists segments_feeder_idx on segments (feeder_id);
create index if not exists defects_feeder_idx  on defects (feeder_id);
create index if not exists events_defect_idx   on defect_events (defect_id);

-- ── event → สถานะจุดบกพร่อง (ผู้รับจ้างแก้ defects เองไม่ได้ จึงให้ trigger ทำ) ──
create or replace function apply_defect_event() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  update defects set
    status   = case new.kind when 'created' then 'open' when 'fix_submitted' then 'submitted' else new.kind end,
    round_no = case when new.kind = 'fix_submitted' then round_no else new.round_no end
  where id = new.defect_id;
  return new;
end $$;
drop trigger if exists trg_defect_event on defect_events;
create trigger trg_defect_event after insert on defect_events for each row execute function apply_defect_event();

-- ════════════════════════════════════════════════════════════════
-- RLS
-- ════════════════════════════════════════════════════════════════
create or replace function my_office() returns text
language sql stable security definer set search_path = public as $$ select office_id from profiles where id = auth.uid() $$;
create or replace function is_inspector() returns boolean
language sql stable security definer set search_path = public as $$ select exists (select 1 from profiles where id = auth.uid() and role = 'inspector') $$;
-- เห็น feeder: ผู้ตรวจ = ทุก feeder ในการไฟฟ้าตน, ผู้รับจ้าง = เฉพาะที่ผูกไว้
create or replace function is_sysadmin() returns boolean
language sql stable security definer set search_path = public as $$ select coalesce((select is_admin from profiles where id = auth.uid()), false) $$;
create or replace function can_see_feeder(f uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from feeders x where x.id = f and x.office_id = my_office()
    and (is_inspector() or exists (select 1 from feeder_contractors fc where fc.feeder_id = f and fc.contractor_id = auth.uid())))
$$;
create or replace function can_edit_feeder(f uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select is_inspector() and exists (select 1 from feeders x where x.id = f and x.office_id = my_office())
$$;

alter table offices            enable row level security;
alter table profiles           enable row level security;
alter table feeders            enable row level security;
alter table feeder_contractors enable row level security;
alter table segments           enable row level security;
alter table inspection_rounds  enable row level security;
alter table defects            enable row level security;
alter table defect_events      enable row level security;

-- หน้า login ต้องเห็นรายชื่อการไฟฟ้าก่อนล็อกอิน
drop policy if exists offices_read on offices;
drop policy if exists offices_write on offices;
create policy offices_read on offices for select using (true);
create policy offices_write on offices for insert to authenticated with check (is_sysadmin());

drop policy if exists profiles_read on profiles;
-- ผู้ใช้เห็นคนในการไฟฟ้าตน · ผู้ดูแลระบบเห็นทุกคน (การสร้าง/แก้บัญชีทำผ่าน Edge Function admin-users เท่านั้น)
create policy profiles_read on profiles for select to authenticated using (office_id = my_office() or is_sysadmin());

drop policy if exists feeders_read on feeders;
drop policy if exists feeders_write on feeders;
create policy feeders_read  on feeders for select to authenticated using (can_see_feeder(id));
create policy feeders_write on feeders for all to authenticated
  using (is_inspector() and office_id = my_office()) with check (is_inspector() and office_id = my_office());

drop policy if exists fc_read on feeder_contractors;
drop policy if exists fc_write on feeder_contractors;
create policy fc_read  on feeder_contractors for select to authenticated using (can_see_feeder(feeder_id));
create policy fc_write on feeder_contractors for all to authenticated using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

drop policy if exists segments_read on segments;
drop policy if exists segments_write on segments;
create policy segments_read  on segments for select to authenticated using (can_see_feeder(feeder_id));
create policy segments_write on segments for all to authenticated using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

drop policy if exists rounds_read on inspection_rounds;
drop policy if exists rounds_write on inspection_rounds;
create policy rounds_read  on inspection_rounds for select to authenticated using (can_see_feeder(feeder_id));
create policy rounds_write on inspection_rounds for all to authenticated using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

drop policy if exists defects_read on defects;
drop policy if exists defects_write on defects;
create policy defects_read  on defects for select to authenticated using (can_see_feeder(feeder_id));
create policy defects_write on defects for all to authenticated using (can_edit_feeder(feeder_id)) with check (can_edit_feeder(feeder_id));

drop policy if exists events_read on defect_events;
drop policy if exists events_insp on defect_events;
drop policy if exists events_con_insert on defect_events;
create policy events_read on defect_events for select to authenticated
  using (exists (select 1 from defects d where d.id = defect_id and can_see_feeder(d.feeder_id)));
create policy events_insp on defect_events for all to authenticated
  using (exists (select 1 from defects d where d.id = defect_id and can_edit_feeder(d.feeder_id)))
  with check (exists (select 1 from defects d where d.id = defect_id and can_edit_feeder(d.feeder_id)));
-- ผู้รับจ้าง: insert ได้อย่างเดียว เฉพาะ fix_submitted ของจุดที่รอแก้/ไม่ผ่าน ใน feeder ตน
create policy events_con_insert on defect_events for insert to authenticated
  with check (kind = 'fix_submitted' and actor_id = auth.uid()
    and exists (select 1 from defects d where d.id = defect_id and d.status in ('open', 'rejected') and can_see_feeder(d.feeder_id)));

-- ════════════════════════════════════════════════════════════════
-- STORAGE: bucket "photos" (private) path {feeder_code}/{defect_id}/{event_id}_{n}.jpg
-- สิทธิ์ตรวจจาก defect_id (โฟลเดอร์ที่ 2) → เห็น feeder นั้นหรือไม่
-- ════════════════════════════════════════════════════════════════
insert into storage.buckets (id, name, public) values ('photos', 'photos', false) on conflict (id) do nothing;

drop policy if exists photos_read on storage.objects;
drop policy if exists photos_insert on storage.objects;
create policy photos_read on storage.objects for select to authenticated
  using (bucket_id = 'photos' and exists (select 1 from defects d where d.id::text = (storage.foldername(name))[2] and can_see_feeder(d.feeder_id)));
create policy photos_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'photos' and exists (select 1 from defects d where d.id::text = (storage.foldername(name))[2] and can_see_feeder(d.feeder_id)));
-- ลบงาน: ผู้ตรวจลบรูปของ feeder ในการไฟฟ้าตน (ต้องลบรูปก่อนลบ feeder เพราะอ้าง defect)
drop policy if exists photos_delete on storage.objects;
create policy photos_delete on storage.objects for delete to authenticated
  using (bucket_id = 'photos' and exists (select 1 from defects d where d.id::text = (storage.foldername(name))[2] and can_edit_feeder(d.feeder_id)));

-- ════════════════════════════════════════════════════════════════
-- REALTIME
-- ════════════════════════════════════════════════════════════════
do $$ begin
  alter publication supabase_realtime add table feeders, segments, defects, defect_events;
exception when duplicate_object then null; end $$;

-- ════════════════════════════════════════════════════════════════
-- สร้างผู้ใช้ (ทำโดยผู้ดูแล — ผู้ใช้ไม่ต้องมีอีเมลจริง)
-- 1) Dashboard → Authentication → Users → Add user → Create new user
--      Email:    {ชื่อผู้ใช้}@{รหัสการไฟฟ้า}.local   เช่น somchai.j@kce.local
--      Password: ตั้งให้ผู้ใช้   ✓ Auto Confirm User
-- 2) รัน SQL ผูกโปรไฟล์ (แก้ค่าตามจริง):
--
-- insert into profiles (id, office_id, username, full_name, role, company)
-- select id, 'kce', 'somchai.j', 'สมชาย ใจดี', 'inspector', null from auth.users where email = 'somchai.j@kce.local';
--
-- insert into profiles (id, office_id, username, full_name, role, company)
-- select id, 'kce', 'romyen.co', 'ผู้ประสานงาน ร่มเย็น', 'contractor', 'หจก. ร่มเย็นการโยธา' from auth.users where email = 'romyen.co@kce.local';
--
-- เพิ่มการไฟฟ้าใหม่: insert into offices values ('xxx', 'กฟส.ชื่อใหม่');
--
-- ตั้งผู้ดูแลระบบ (จัดการการไฟฟ้าและผู้ใช้ในแอปได้ — ต้อง deploy Edge Function supabase/functions/admin-users ด้วย):
-- update profiles set is_admin = true where office_id = 'kce' and username = 'admin';
-- ════════════════════════════════════════════════════════════════
